# Generated by Django 3.2.13 on 2023-04-26 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_alter_domainmanage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainanalysis',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.domainmanage', verbose_name='关联域名名称'),
        ),
    ]
