# Generated by Django 3.2.13 on 2023-04-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_auto_20230426_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainanalysis',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='domainmanage',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
