# Generated by Django 3.2.13 on 2023-04-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_auto_20230426_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmanage',
            name='status',
            field=models.CharField(max_length=20, verbose_name='域名状态'),
        ),
    ]
