# Generated by Django 3.2.13 on 2023-04-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0007_alter_domainmanage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmanage',
            name='ExpirationTime',
            field=models.IntegerField(blank=True, null=True, verbose_name='过期时间提示'),
        ),
        migrations.AlterField(
            model_name='domainmanage',
            name='create_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='domainmanage',
            name='expire_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='到期时间'),
        ),
    ]
