# Generated by Django 3.2.13 on 2023-04-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0008_auto_20230427_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmanage',
            name='ExpirationDateStatus',
            field=models.CharField(blank=True, choices=[('1', '域名未过期'), ('2', '域名已过期')], default='1', max_length=20, null=True, verbose_name='域名过期状态'),
        ),
        migrations.AlterField(
            model_name='domainmanage',
            name='ExpirationTime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='过期时间提示'),
        ),
        migrations.AlterField(
            model_name='domainmanage',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='域名状态'),
        ),
    ]
