# Generated by Django 3.2.13 on 2023-01-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='机房名称')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('provider', models.CharField(max_length=30, verbose_name='运营商')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': 'IDC机房',
                'db_table': 'cmdb_idc',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PhysicsServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='名称')),
                ('hostname', models.CharField(max_length=30, unique=True, verbose_name='主机名')),
                ('ssh_ip', models.GenericIPAddressField(verbose_name='远程连接IP')),
                ('ssh_port', models.IntegerField(verbose_name='远程连接端口')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('machine_type', models.CharField(blank=True, choices=[('windows', 'windows'), ('linux', 'linux'), ('vmware', 'vmware')], default='linux', max_length=30, verbose_name='机器类型')),
                ('asset_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='资产编码')),
                ('os_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='系统版本')),
                ('public_ip', models.JSONField(blank=True, max_length=100, null=True, verbose_name='公网IP')),
                ('private_ip', models.JSONField(blank=True, max_length=100, null=True, verbose_name='内网IP')),
                ('cpu_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='CPU')),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU型号')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='内存')),
                ('disk', models.JSONField(blank=True, max_length=200, null=True, verbose_name='硬盘')),
                ('network', models.CharField(blank=True, max_length=200, null=True, verbose_name='带宽')),
                ('put_shelves_date', models.DateField(blank=True, null=True, verbose_name='上架日期')),
                ('off_shelves_date', models.DateField(blank=True, null=True, verbose_name='下架日期')),
                ('is_verified', models.CharField(blank=True, choices=[('verified', '已验证'), ('unverified', '未验证')], default='unverified', max_length=10, verbose_name='SSH验证状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system_config.credential', verbose_name='凭据')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.idc', verbose_name='IDC机房')),
            ],
            options={
                'verbose_name_plural': '物理机管理',
                'db_table': 'cmdb_physics_server',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='分组名称')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '主机分组',
                'db_table': 'cmdb_server_group',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VmServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='名称')),
                ('hostname', models.CharField(max_length=30, unique=True, verbose_name='主机名')),
                ('ssh_ip', models.GenericIPAddressField(verbose_name='远程连接IP')),
                ('ssh_port', models.IntegerField(verbose_name='远程连接端口')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('machine_type', models.CharField(blank=True, choices=[('windows', 'windows'), ('linux', 'linux')], default='linux', max_length=30, verbose_name='机器类型')),
                ('os_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='系统版本')),
                ('public_ip', models.JSONField(blank=True, max_length=100, null=True, verbose_name='公网IP')),
                ('private_ip', models.JSONField(blank=True, max_length=100, null=True, verbose_name='内网IP')),
                ('cpu_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='CPU')),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU型号')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='内存')),
                ('disk', models.JSONField(blank=True, max_length=200, null=True, verbose_name='硬盘')),
                ('network', models.CharField(blank=True, max_length=200, null=True, verbose_name='带宽')),
                ('put_shelves_date', models.DateField(blank=True, null=True, verbose_name='上架日期')),
                ('off_shelves_date', models.DateField(blank=True, null=True, verbose_name='下架日期')),
                ('is_verified', models.CharField(blank=True, choices=[('verified', '已验证'), ('unverified', '未验证')], default='unverified', max_length=10, verbose_name='SSH验证状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system_config.credential', verbose_name='凭据')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.idc', verbose_name='IDC机房')),
                ('server_group', models.ManyToManyField(default='Default', to='cmdb.ServerGroup', verbose_name='主机分组')),
                ('vm_host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.physicsserver', verbose_name='虚拟主机')),
            ],
            options={
                'verbose_name_plural': '虚拟机管理',
                'db_table': 'cmdb_vm_server',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='physicsserver',
            name='server_group',
            field=models.ManyToManyField(default='Default', to='cmdb.ServerGroup', verbose_name='主机分组'),
        ),
        migrations.CreateModel(
            name='CloudServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='名称')),
                ('hostname', models.CharField(max_length=30, unique=True, verbose_name='主机名')),
                ('ssh_ip', models.GenericIPAddressField(verbose_name='远程连接IP')),
                ('ssh_port', models.IntegerField(verbose_name='远程连接端口')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('machine_type', models.CharField(blank=True, choices=[('windows', 'windows'), ('linux', 'linux')], default='linux', max_length=30, verbose_name='机器类型')),
                ('os_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='系统版本')),
                ('public_ip', models.JSONField(blank=True, max_length=100, null=True, verbose_name='公网IP')),
                ('private_ip', models.JSONField(blank=True, max_length=100, null=True, verbose_name='内网IP')),
                ('cpu_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='内存')),
                ('disk', models.JSONField(blank=True, max_length=200, null=True, verbose_name='硬盘')),
                ('network', models.CharField(blank=True, max_length=200, null=True, verbose_name='带宽')),
                ('put_shelves_date', models.DateField(blank=True, null=True, verbose_name='上架日期')),
                ('off_shelves_date', models.DateField(blank=True, null=True, verbose_name='下架日期')),
                ('expire_datetime', models.DateTimeField(blank=True, null=True, verbose_name='租约过期时间')),
                ('is_verified', models.CharField(blank=True, choices=[('verified', '已验证'), ('unverified', '未验证')], default='unverified', max_length=10, verbose_name='SSH验证状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system_config.credential', verbose_name='凭据')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.idc', verbose_name='IDC机房')),
                ('server_group', models.ManyToManyField(default='Default', to='cmdb.ServerGroup', verbose_name='主机分组')),
            ],
            options={
                'verbose_name_plural': '云主机管理',
                'db_table': 'cmdb_cloud_server',
                'ordering': ('-id',),
            },
        ),
    ]
