# Generated by Django 3.2.9 on 2022-12-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud_server',
            name='cpu_model',
        ),
    ]
