# Generated by Django 3.2.9 on 2022-12-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_remove_cloud_server_cpu_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloud_server',
            options={'ordering': ('-id',), 'verbose_name_plural': '云主机管理'},
        ),
        migrations.AlterModelOptions(
            name='physics_server',
            options={'ordering': ('-id',), 'verbose_name_plural': '物理机管理'},
        ),
        migrations.AlterModelOptions(
            name='vm_server',
            options={'ordering': ('-id',), 'verbose_name_plural': '虚拟机管理'},
        ),
        migrations.RemoveField(
            model_name='vm_server',
            name='asset_code',
        ),
    ]
