# Generated by Django 3.2.9 on 2023-01-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20221230_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud_server',
            name='machine_type',
            field=models.CharField(blank=True, choices=[('windows', 'windows'), ('linux', 'linux')], default='linux', max_length=30, verbose_name='机器类型'),
        ),
        migrations.AlterField(
            model_name='cloud_server',
            name='ssh_ip',
            field=models.GenericIPAddressField(verbose_name='远程连接IP'),
        ),
        migrations.AlterField(
            model_name='cloud_server',
            name='ssh_port',
            field=models.IntegerField(verbose_name='远程连接端口'),
        ),
        migrations.AlterField(
            model_name='physics_server',
            name='machine_type',
            field=models.CharField(blank=True, choices=[('windows', 'windows'), ('linux', 'linux')], default='linux', max_length=30, verbose_name='机器类型'),
        ),
        migrations.AlterField(
            model_name='physics_server',
            name='ssh_ip',
            field=models.GenericIPAddressField(verbose_name='远程连接IP'),
        ),
        migrations.AlterField(
            model_name='physics_server',
            name='ssh_port',
            field=models.IntegerField(verbose_name='远程连接端口'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='machine_type',
            field=models.CharField(blank=True, choices=[('windows', 'windows'), ('linux', 'linux')], default='linux', max_length=30, verbose_name='机器类型'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='ssh_ip',
            field=models.GenericIPAddressField(verbose_name='远程连接IP'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='ssh_port',
            field=models.IntegerField(verbose_name='远程连接端口'),
        ),
    ]
