# Generated by Django 3.2.9 on 2023-01-03 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20221230_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='机器类型名称')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '机器类型',
                'db_table': 'cmdb_machine_type',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='cloud_server',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.machinetype', verbose_name='机房类型'),
        ),
        migrations.AlterField(
            model_name='physics_server',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.machinetype', verbose_name='机房类型'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cmdb.machinetype', verbose_name='机房类型'),
        ),
    ]
