# Generated by Django 3.2.9 on 2023-01-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20230103_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud_server',
            name='disk',
            field=models.JSONField(blank=True, max_length=200, null=True, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='cloud_server',
            name='private_ip',
            field=models.JSONField(blank=True, max_length=100, null=True, verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='cloud_server',
            name='public_ip',
            field=models.JSONField(blank=True, max_length=100, null=True, verbose_name='公网IP'),
        ),
        migrations.AlterField(
            model_name='physics_server',
            name='disk',
            field=models.JSONField(blank=True, max_length=200, null=True, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='physics_server',
            name='private_ip',
            field=models.JSONField(blank=True, max_length=100, null=True, verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='physics_server',
            name='public_ip',
            field=models.JSONField(blank=True, max_length=100, null=True, verbose_name='公网IP'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='disk',
            field=models.JSONField(blank=True, max_length=200, null=True, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='private_ip',
            field=models.JSONField(blank=True, max_length=100, null=True, verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='vm_server',
            name='public_ip',
            field=models.JSONField(blank=True, max_length=100, null=True, verbose_name='公网IP'),
        ),
    ]
